PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT ?title ?doc ?contributor ?contributor_name ?contributor_role WHERE {
  ?doc ?relator $organization; dcterms:bibliographicCitation ?title.
  ?doc ?person_relator ?contributor .
  ?contributor a foaf:Person .
  OPTIONAL {
    ?contributor skos:prefLabel ?contributor_name .
    ?person_relator skos:prefLabel ?contributor_role .
  }
} GROUP BY ?doc
