# IdRef — Person contributions (co-authors)
# Retrieve publications where a person contributed, with co-authors.
#
# Parameters:
#   $person  (URI)  — IdRef person URI

PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX marcrel: <http://id.loc.gov/vocabulary/relators/>

SELECT DISTINCT ?title ?role ?doc ?author ?author_name WHERE {
  ?doc ?relator $person; dcterms:bibliographicCitation ?title.
  ?relator skos:prefLabel ?role.
  ?doc marcrel:aut ?author.
  ?author skos:prefLabel ?author_name.
} GROUP BY ?doc
