# IdRef — Person detail
# Retrieve detailed information about a person by IdRef URI.
#
# Parameters:
#   $person  (URI)  — IdRef person URI, e.g. <http://www.idref.fr/121375307/id>

PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX marcrel: <http://id.loc.gov/vocabulary/relators/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX org: <http://www.w3.org/ns/org#>

SELECT DISTINCT ?name ?note ?org ?orgName WHERE {
  $person
    skos:prefLabel ?name ;
    skos:note ?note .

  OPTIONAL {
    $person org:memberOf ?org .

    {
      SELECT ?org (SAMPLE(?label) AS ?orgName)
      WHERE {
        ?org skos:prefLabel ?label .
      }
      GROUP BY ?org
    }
  }
}
