# IdRef — Co-authors via shared publications
# Find co-authors for a given IdRef person by looking at shared publications.
#
# Parameters:
#   $person (URI) — IdRef person URI, e.g. <http://www.idref.fr/139753753/id>

PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX marcrel: <http://id.loc.gov/vocabulary/relators/>

SELECT DISTINCT ?auturi ?aut
  (GROUP_CONCAT(DISTINCT ?uri; SEPARATOR=" | ") AS ?uris)
  (GROUP_CONCAT(DISTINCT ?titre; SEPARATOR=" | ") AS ?titres)
WHERE {
  ?uri marcrel:aut $person.
  ?uri dcterms:bibliographicCitation ?titre.
  ?uri marcrel:aut ?auturi.
  ?auturi skos:prefLabel ?aut.
  FILTER (?auturi != $person)
} GROUP BY ?auturi ?aut
