# HAL — Contributors to a publication
# Retrieve all contributors (authors) for a given HAL publication.
#
# Parameters:
#   $publication_id (URI) — HAL publication URI

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT ?authuri ?auth ?title
WHERE {
  $publication_id foaf:name ?title.
  ?authuri foaf:publications $publication_id.
  ?authuri foaf:name ?auth.
}
