/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Traverse Graph
         * @description Progressive graph exploration starting from a root entity.
         *
         *     Returns a bounded Neighborhood: the center entity, all discovered
         *     nodes, and the edges between them.
         */
        get: operations["traverse_graph_api_graph__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/person/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Person
         * @description Get detailed information about a person from IdRef.
         *
         *     Accepts raw PPN (e.g. "121375307") or full IdRef URI
         *     (e.g. "http://www.idref.fr/121375307/id").
         */
        get: operations["get_person_api_person__person_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publication/{publication_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Publication
         * @description Get detailed information about a publication.
         */
        get: operations["get_publication_api_publication__publication_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organization/{organization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Organization
         * @description Get detailed information about an organization from IdRef.
         *
         *     Accepts raw PPN (e.g. "227816196") or full IdRef URI
         *     (e.g. "http://www.idref.fr/227816196/id").
         */
        get: operations["get_organization_api_organization__organization_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Search for persons and organizations in IdRef via SOLR.
         */
        get: operations["search_api_search__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root_api_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Dataset
         * @description The data source from which a relationship was retrieved.
         */
        Dataset: {
            /** Name */
            name: string;
            /** Endpoint */
            endpoint?: string | null;
        };
        /**
         * Entity
         * @description Base node in the academic graph.
         *
         *     Subclasses: Person, Organization, Publication.
         *     The `type` discriminator ensures Pydantic serializes the concrete type
         *     even when held in a list[Entity] (e.g., Neighborhood.nodes).
         */
        Entity: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            type: components["schemas"]["EntityType"];
            /**
             * Identifiers
             * @default []
             */
            identifiers: components["schemas"]["Identifier"][];
        };
        /**
         * EntityType
         * @enum {string}
         */
        EntityType: "person" | "publication" | "organization";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Identifier
         * @description An external identifier (ORCID, DOI, ROR, IdRef, etc.).
         */
        Identifier: {
            /** Scheme */
            scheme: string;
            /** Value */
            value: string;
        };
        /**
         * Neighborhood
         * @description A bounded neighborhood of the graph around a central entity.
         */
        Neighborhood: {
            center: components["schemas"]["Entity"];
            /** Nodes */
            nodes: (components["schemas"]["Person"] | components["schemas"]["Organization"] | components["schemas"]["Publication"])[];
            /** Edges */
            edges: components["schemas"]["Relationship"][];
        };
        /**
         * Organization
         * @description An organization (institution, lab, funder, etc.).
         */
        Organization: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "organization";
            /**
             * Identifiers
             * @default []
             */
            identifiers: components["schemas"]["Identifier"][];
            /** Note */
            note?: string | null;
        };
        /**
         * Person
         * @description A person (researcher, author, director, etc.).
         *
         *     Limited to simple self-referencing: person has Organization
         *     memberships. Organization is defined before Person to avoid
         *     forward-reference issues with Pydantic.
         */
        Person: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "person";
            /**
             * Identifiers
             * @default []
             */
            identifiers: components["schemas"]["Identifier"][];
            /** Note */
            note?: string | null;
            /**
             * Organizations
             * @default []
             */
            organizations: components["schemas"]["Organization"][];
        };
        /**
         * Publication
         * @description A publication (article, book, thesis, etc.).
         */
        Publication: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "publication";
            /**
             * Identifiers
             * @default []
             */
            identifiers: components["schemas"]["Identifier"][];
            /** Doi */
            doi?: string | null;
        };
        /**
         * Relationship
         * @description A directional relationship between two entities.
         *
         *     The `type` field carries the role from the data source
         *     (e.g., "author", "directedBy", "host"). It is free-form.
         */
        Relationship: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
            source_dataset: components["schemas"]["Dataset"];
        };
        /**
         * SearchResult
         * @description A search result from IdRef SOLR.
         */
        SearchResult: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    traverse_graph_api_graph__get: {
        parameters: {
            query: {
                /** @description Starting entity ID (PPN or full URI) */
                root: string;
                /** @description Entity type: person, organization, or publication */
                type: string;
                /** @description Number of hops from root */
                depth?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Neighborhood"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_api_person__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_publication_api_publication__publication_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Publication"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organization_api_organization__organization_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search__get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root_api_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
